project_name: fofadump

builds:
  - env: [ CGO_ENABLED=0 ]

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - 386
      - amd64
      - arm64

    ignore:
      - goos: darwin
        goarch: 386

    main: ./cmd/fofadump
